import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import StyledComponentsRegistry from '@/components/AntdRegistry';
import { Header } from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Interview nextjs',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <StyledComponentsRegistry>
            <main>
              <Header />
              <div className="bg-body h-[calc(100vh-135px)] pt-36">
                {children}
              </div>
            </main>
          </StyledComponentsRegistry>
        </body>
      </html>
    </ClerkProvider>
  );
}
